export interface Financials {
     Symbol: string;
    Name: string;
    Sector: string;
    Price: string;
    'Dividend Yield': string;
    'Price/Earnings': string;
    'Earnings/Share': string;
    'Book Value': string;
    '52 week low': string;
    '52 week high': string;
    "Market Cap": string;
    "EBITDA": string;
    "Price/Sales": string;
    "Price/Book": string;
    "SEC Filings" : string;
}

export class FinancialDetail {
    "symbol": string;
    "Ask": string;
    "AverageDailyVolume": string;
    "Bid": string;
    "AskRealtime": string;
    "BidRealtime": string;
    "BookValue": string;
    "Change_PercentChange": string;
    "Change": string;
    "Commission": string;
    "Currency": "USD";
    "ChangeRealtime": string;
    "AfterHoursChangeRealtime": string;
    "DividendShare": string;
    "LastTradeDate": string;
    "TradeDate": string;
    "EarningsShare": string;
    "ErrorIndicationreturnedforsymbolchangedinvalid": string;
    "EPSEstimateCurrentYear": string;
    "EPSEstimateNextYear": string;
    "EPSEstimateNextQuarter": string;
    "DaysLow": string;
    "DaysHigh": string;
    "YearLow": string;
    "YearHigh": string;
    "HoldingsGainPercent": string;
    "AnnualizedGain": string;
    "HoldingsGain": string;
    "HoldingsGainPercentRealtime": string;
    "HoldingsGainRealtime": string;
    "MoreInfo": string;
    "OrderBookRealtime": string;
    "MarketCapitalization": string;
    "MarketCapRealtime": string;
    "EBITDA": string;
    "ChangeFromYearLow": string;
    "PercentChangeFromYearLow": string;
    "LastTradeRealtimeWithTime": string;
    "ChangePercentRealtime": string;
    "ChangeFromYearHigh": string;
    "PercebtChangeFromYearHigh": string;
    "LastTradeWithTime": string;
    "LastTradePriceOnly": string;
    "HighLimit": string;
    "LowLimit": string;
    "DaysRange": string;
    "DaysRangeRealtime": string;
    "FiftydayMovingAverage": string;
    "TwoHundreddayMovingAverage": string;
    "ChangeFromTwoHundreddayMovingAverage": string;
    "PercentChangeFromTwoHundreddayMovingAverage": string;
    "ChangeFromFiftydayMovingAverage":string;
    "PercentChangeFromFiftydayMovingAverage": string;
    "Name": string;
    "Notes": string;
    "Open": string;
    "PreviousClose": string;
    "PricePaid": string;
    "ChangeinPercent": string;
    "PriceSales":string;
    "PriceBook": string;
    "ExDividendDate": string;
    "PERatio": string;
    "DividendPayDate": string;
    "PERatioRealtime": string;
    "PEGRatio": string;
    "PriceEPSEstimateCurrentYear": string;
    "PriceEPSEstimateNextYear": string;
    "Symbol": string;
    "SharesOwned": string;
    "ShortRatio": string;
    "LastTradeTime": string;
    "TickerTrend": string;
    "OneyrTargetPrice": string;
    "Volume": string;
    "HoldingsValue": string;
    "HoldingsValueRealtime": string;
    "YearRange": string;
    "DaysValueChange": string;
    "DaysValueChangeRealtime": string;
    "StockExchange": string;
    "DividendYield": string;
    "PercentChange": string;
};